apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
stringData:
  KEYCLOAK_SERVICE_ACCOUNT_ID: {{ .Values.keycloak.serviceAccountId }}
  KEYCLOAK_SERVICE_ACCOUNT_SECRET: {{ .Values.keycloak.serviceAccountSecret }}
  DATABASE_PASSWORD: {{ .Values.database.submit.password }}
  CENTRE_DATABASE_PASSWORD: {{ .Values.database.centre.password }}